# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c94c4e7f39514f3a9f7b290f5969b1e21f63dbba31e2fc4edab2a3b114916438722d3097766fddb15810d286fd240ed1e3c05058098080378b6866966aaceb0e

test:
  secret_key_base: f771b8d4a1a1fdd659a2713941f4d227d2d19ae43e3808ec7fe5854bccbd8d24975f0c6984f137c85fc503dbbe651741c495f2fcb69b9934bec8c6a9719aac91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
